route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
        - send_resolved: true
          title: "{{ .CommonAnnotations.summary }}"
          text: "{{ .CommonAnnotations.description }}"
          username: 'jsongo'
          channel: '#alert0'
          api_url: 'https://hooks.slack.com/services/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'
