version: '3'

services:

  prometheus:
    image: prom/prometheus
    #restart: always
    container_name: prometheus
    network_mode: "bridge"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      #- '--alertmanager.url=http://alertmanager:27840'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 37828:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor

  alertmanager:
    network_mode: "bridge"
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 27840:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    #restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    network_mode: "bridge"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 33899:8080
    #restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: "bridge"
    depends_on:
      - prometheus
    ports:
      - 49501:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    env_file:
      - config.monitoring
