input:
    type: file
    path: /log/access.log
    readall: true
grok:
    patterns_dir: /patterns
metrics:
    - type: counter
      name: grok_nginx
      help: Metrics for nginx.
      match: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
server:
    port: 9145