input:
    type: file
    path: /log/access.log
    readall: true
grok:
    patterns_dir: /data/patterns
    additional_patterns:
    - 'NGUSERNAME [a-zA-Z\.\@\-\+_%]+'
    - 'NGUSER %{NGUSERNAME}'
metrics:
    - type: counter
      name: grok_nginx
      help: Metrics for nginx.
      match: "%{IPORHOST:clientip} (?:%{NGUSER:ident}|-) (?:%{NGUSER:auth}|-) [%{HTTPDATE:timestamp}] \"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|-)\" %{NUMBER:status} (?:%{NUMBER:bytes}|-) (?:\"(?:%{URI:referrer}|-)\"|%{QS:referrer}) \"%{QS:agent}\""
server:
    port: 9145
